{
    'name': 'EVENT MANAGEMENT',
    'version': '14.0.1.0',
    'category': '',
    'sequence': 15,
    'summary': '',
    'description': "event management module",
    'depends': ['contacts', 'mail', 'account'],
    'data': ['security/ir.model.access.csv',
             'security/event_types_security.xml',
             'data/seq.xml',
             'views/event_types_view.xml',
             'views/event_booking_view.xml',
             'views/service.xml',
             'views/catering.xml',
             'views/catering_dish.xml',
             'views/catering_invoice.xml',
             'demo/demo_type.xml'],
    'demo': ['demo/demo_type.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}